export interface Video {
  videoId: string;
  title: string;
  channelName: string;
  channelId: string;
  thumbnailUrl: string;
  publishedAt: string;
  description: string;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  duration: string;
  category: string;
}

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_VIDEOS: Video[] = [
  {
    videoId: 'dQw4w9WgXcQ',
    title: 'Top 10 Football Goals of the Season - Incredible Highlights',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    publishedAt: hoursAgo(2),
    description: 'Watch the most incredible football goals scored this season. From long-range screamers to delicate chips, these goals will leave you speechless. Featuring goals from the Premier League, La Liga, Champions League, and more.',
    viewCount: 2500000,
    likeCount: 85000,
    commentCount: 4200,
    duration: '12:34',
    category: 'Football',
  },
  {
    videoId: 'ScMzIvxBSi4',
    title: 'NBA Playoffs Recap: Warriors vs Celtics Game 7 Highlights',
    channelName: 'NBA',
    channelId: 'UCWJ2lWNubArHWmf3FIHbfcQ',
    thumbnailUrl: 'https://i.ytimg.com/vi/ScMzIvxBSi4/mqdefault.jpg',
    publishedAt: hoursAgo(5),
    description: 'Full highlights from Game 7 of the NBA Finals. Stephen Curry led the Warriors with 43 points while Jayson Tatum tried to keep the Celtics in it. The ultimate showdown for the Larry O\'Brien trophy.',
    viewCount: 5200000,
    likeCount: 180000,
    commentCount: 15000,
    duration: '18:22',
    category: 'Basketball',
  },
  {
    videoId: 'YrNGAhMOiXc',
    title: 'UFC 310: Main Card Highlights - Makhachev vs Oliveira 3',
    channelName: 'UFC',
    channelId: 'UCvgfXK4aHYobs0s2FhW6pNg',
    thumbnailUrl: 'https://i.ytimg.com/vi/YrNGAhMOiXc/mqdefault.jpg',
    publishedAt: hoursAgo(8),
    description: 'Watch all the best moments from UFC 310 main card. Islam Makhachev defends his lightweight title against Charles Oliveira in their trilogy fight. Plus all the co-main event action.',
    viewCount: 3800000,
    likeCount: 120000,
    commentCount: 8900,
    duration: '15:47',
    category: 'MMA',
  },
  {
    videoId: '9bZkp7q19f0',
    title: 'Champions League Semi-Final: Real Madrid vs Manchester City - Full Match Analysis',
    channelName: 'Sky Sports',
    channelId: 'UCDjFJ-YdsJ3VT2zBOPOdqeA',
    thumbnailUrl: 'https://i.ytimg.com/vi/9bZkp7q19f0/mqdefault.jpg',
    publishedAt: daysAgo(1),
    description: 'A comprehensive tactical breakdown of the Champions League semi-final between Real Madrid and Manchester City. Our panel of experts analyze every key moment, tactical decision, and game-changing play.',
    viewCount: 1800000,
    likeCount: 52000,
    commentCount: 6300,
    duration: '22:15',
    category: 'Football',
  },
  {
    videoId: 'kJQP7kiw5Fk',
    title: 'IPL 2025: Record-Breaking Season - Best Moments Compilation',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/mqdefault.jpg',
    publishedAt: daysAgo(1),
    description: 'The Indian Premier League 2025 delivered some of the most exciting cricket ever played. From record-breaking centuries to last-ball thrillers, relive every incredible moment.',
    viewCount: 4500000,
    likeCount: 156000,
    commentCount: 11000,
    duration: '20:08',
    category: 'Cricket',
  },
  {
    videoId: 'RgKAFK5djSk',
    title: 'Wimbledon 2025 Preview: Can Anyone Stop Djokovic?',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/RgKAFK5djSk/mqdefault.jpg',
    publishedAt: daysAgo(2),
    description: 'A deep dive into the Wimbledon 2025 Championships. Novak Djokovic goes for his record 9th title, while Carlos Alcaraz and Jannik Sinner look to dethrone the king of grass courts.',
    viewCount: 980000,
    likeCount: 34000,
    commentCount: 2800,
    duration: '14:33',
    category: 'Tennis',
  },
  {
    videoId: '60ItHLz5WEA',
    title: 'MLB Home Run Derby 2025: Unbelievable Power Display',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/60ItHLz5WEA/mqdefault.jpg',
    publishedAt: daysAgo(3),
    description: 'The 2025 Home Run Derby delivered some of the longest and most impressive home runs in the event\'s history. Watch every moonshot from the brightest stars in Major League Baseball.',
    viewCount: 1200000,
    likeCount: 45000,
    commentCount: 3200,
    duration: '16:55',
    category: 'Baseball',
  },
  {
    videoId: 'fJ9rUzIMcZQ',
    title: 'Transfer Window LIVE: All Major Deals & Rumors Roundup',
    channelName: 'Sky Sports',
    channelId: 'UCDjFJ-YdsJ3VT2zBOPOdqeA',
    thumbnailUrl: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/mqdefault.jpg',
    publishedAt: hoursAgo(12),
    description: 'All the latest transfer news, completed deals, and breaking rumors from across Europe\'s top leagues.Mbappe\'s next move, Haaland\'s contract situation, and every major story covered.',
    viewCount: 890000,
    likeCount: 22000,
    commentCount: 7500,
    duration: '25:10',
    category: 'Football',
  },
  {
    videoId: 'pRpeEdMmmQ0',
    title: 'LeBron James Career Retrospective: The GOAT Debate Settled?',
    channelName: 'NBA',
    channelId: 'UCWJ2lWNubArHWmf3FIHbfcQ',
    thumbnailUrl: 'https://i.ytimg.com/vi/pRpeEdMmmQ0/mqdefault.jpg',
    publishedAt: daysAgo(4),
    description: 'An in-depth look at LeBron James\' incredible 20+ year NBA career. From his debut as the Chosen One to becoming the NBA\'s all-time leading scorer, relive every iconic moment.',
    viewCount: 6700000,
    likeCount: 230000,
    commentCount: 28000,
    duration: '30:22',
    category: 'Basketball',
  },
  {
    videoId: 'hT_nvWreIhg',
    title: 'UFC Top 5 Knockouts of 2025 So Far',
    channelName: 'UFC',
    channelId: 'UCvgfXK4aHYobs0s2FhW6pNg',
    thumbnailUrl: 'https://i.ytimg.com/vi/hT_nvWreIhg/mqdefault.jpg',
    publishedAt: daysAgo(5),
    description: 'The five most devastating knockouts in the UFC this year. From spinning elbows to one-punch finishes, these finishes will have you on the edge of your seat.',
    viewCount: 4200000,
    likeCount: 145000,
    commentCount: 9800,
    duration: '8:45',
    category: 'MMA',
  },
  {
    videoId: 'OPf0YbXqDm0',
    title: 'Premier League Transfer News: Arsenal Close In On Major Signing',
    channelName: 'Sky Sports',
    channelId: 'UCDjFJ-YdsJ3VT2zBOPOdqeA',
    thumbnailUrl: 'https://i.ytimg.com/vi/OPf0YbXqDm0/mqdefault.jpg',
    publishedAt: daysAgo(1),
    description: 'Arsenal are reportedly close to completing a major transfer deal that could transform their title challenge. We break down all the details and what it means for the Gunners.',
    viewCount: 750000,
    likeCount: 18000,
    commentCount: 4100,
    duration: '7:20',
    category: 'Football',
  },
  {
    videoId: 'CevxZvSJLk8',
    title: 'T20 World Cup 2025: India vs Australia - Thrilling Final Highlights',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/CevxZvSJLk8/mqdefault.jpg',
    publishedAt: daysAgo(6),
    description: 'Relive the dramatic T20 World Cup final between India and Australia. A match that went down to the wire with incredible performances from both sides. Cricket at its finest.',
    viewCount: 8200000,
    likeCount: 340000,
    commentCount: 42000,
    duration: '19:30',
    category: 'Cricket',
  },
  {
    videoId: 'e-ORhEE9VVg',
    title: 'Federer vs Nadal: Greatest Rivalry in Tennis History - Documentary',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/e-ORhEE9VVg/mqdefault.jpg',
    publishedAt: daysAgo(7),
    description: 'A comprehensive documentary chronicling the greatest rivalry in tennis history. From their first meeting in 2004 to their legendary matches at Wimbledon and the Australian Open.',
    viewCount: 3400000,
    likeCount: 95000,
    commentCount: 7200,
    duration: '45:18',
    category: 'Tennis',
  },
  {
    videoId: 'JGwWNGJdvx8',
    title: 'NFL Draft 2025: Top Picks & Biggest Surprises',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/JGwWNGJdvx8/mqdefault.jpg',
    publishedAt: daysAgo(8),
    description: 'Complete coverage of the 2025 NFL Draft. Who were the biggest steals? Which teams made the boldest moves? Our experts break down every pick in the first round.',
    viewCount: 1900000,
    likeCount: 56000,
    commentCount: 8900,
    duration: '28:44',
    category: 'Other',
  },
  {
    videoId: 'HQmmM_qwG4k',
    title: 'F1 2025: Monaco Grand Prix Highlights - Drama on the Streets',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/HQmmM_qwG4k/mqdefault.jpg',
    publishedAt: daysAgo(9),
    description: 'The most glamorous race on the F1 calendar delivered incredible drama. Overtakes, crashes, and strategy battles on the tight streets of Monte Carlo.',
    viewCount: 2100000,
    likeCount: 67000,
    commentCount: 5100,
    duration: '14:22',
    category: 'Other',
  },
  {
    videoId: 'DyDfgMOUjCI',
    title: 'MMA Training Secrets: How Champions Prepare for Fight Night',
    channelName: 'UFC',
    channelId: 'UCvgfXK4aHYobs0s2FhW6pNg',
    thumbnailUrl: 'https://i.ytimg.com/vi/DyDfgMOUjCI/mqdefault.jpg',
    publishedAt: daysAgo(3),
    description: 'Go behind the scenes of how UFC champions train for their biggest fights. From strength and conditioning to sparring sessions, see what it takes to compete at the highest level.',
    viewCount: 2800000,
    likeCount: 98000,
    commentCount: 6700,
    duration: '17:55',
    category: 'MMA',
  },
  {
    videoId: 'L_jWHffIx5E',
    title: 'Basketball Tricks & Skills Challenge - NBA Stars Go Head to Head',
    channelName: 'NBA',
    channelId: 'UCWJ2lWNubArHWmf3FIHbfcQ',
    thumbnailUrl: 'https://i.ytimg.com/vi/L_jWHffIx5E/mqdefault.jpg',
    publishedAt: daysAgo(10),
    description: 'Watch NBA superstars compete in an epic skills and tricks challenge. From half-court shots to dribbling exhibitions, see the best basketball players in the world show off their incredible talent.',
    viewCount: 5600000,
    likeCount: 195000,
    commentCount: 13000,
    duration: '11:30',
    category: 'Basketball',
  },
  {
    videoId: 'hLQl3WQQoQ0',
    title: 'Premier League Goals of the Month - May 2025',
    channelName: 'Sky Sports',
    channelId: 'UCDjFJ-YdsJ3VT2zBOPOdqeA',
    thumbnailUrl: 'https://i.ytimg.com/vi/hLQl3WQQoQ0/mqdefault.jpg',
    publishedAt: daysAgo(2),
    description: 'The best goals scored in the Premier League during May 2025. Spectacular strikes, team goals, and individual brilliance - all the best moments from the final weeks of the season.',
    viewCount: 1400000,
    likeCount: 41000,
    commentCount: 2900,
    duration: '10:15',
    category: 'Football',
  },
  {
    videoId: '1w7OgIMMRc4',
    title: 'MLB Season Preview 2025: Teams Most Likely to Win the World Series',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/1w7OgIMMRc4/mqdefault.jpg',
    publishedAt: daysAgo(11),
    description: 'Our baseball experts predict which teams have the best shot at winning the 2025 World Series. Full analysis of rosters, off-season moves, and key storylines for all 30 MLB teams.',
    viewCount: 850000,
    likeCount: 28000,
    commentCount: 3400,
    duration: '21:40',
    category: 'Baseball',
  },
  {
    videoId: 'YQHsXMglC9A',
    title: 'Cricket World Test Championship Final: Complete Highlights',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/YQHsXMglC9A/mqdefault.jpg',
    publishedAt: daysAgo(12),
    description: 'Full highlights from the ICC World Test Championship Final. Five days of intense Test cricket came down to a dramatic final session. Every key moment from this historic match.',
    viewCount: 2100000,
    likeCount: 78000,
    commentCount: 5600,
    duration: '35:12',
    category: 'Cricket',
  },
  {
    videoId: 'F09uGw0OgHQ',
    title: 'UFC 309 Post-Fight Press Conference - Jones Speaks',
    channelName: 'UFC',
    channelId: 'UCvgfXK4aHYobs0s2FhW6pNg',
    thumbnailUrl: 'https://i.ytimg.com/vi/F09uGw0OgHQ/mqdefault.jpg',
    publishedAt: daysAgo(4),
    description: 'Jon Jones speaks after his dominant performance at UFC 309. The undisputed champion addresses his future, potential superfights, and sends a message to the rest of the light heavyweight division.',
    viewCount: 3100000,
    likeCount: 110000,
    commentCount: 12000,
    duration: '42:30',
    category: 'MMA',
  },
  {
    videoId: 'QH2-TGUlwu4',
    title: 'La Liga Title Race: Barcelona vs Real Madrid Decider Preview',
    channelName: 'ESPN',
    channelId: 'UCiiljEMOGL7SUhPCrCO-MOg',
    thumbnailUrl: 'https://i.ytimg.com/vi/QH2-TGUlwu4/mqdefault.jpg',
    publishedAt: daysAgo(5),
    description: 'Everything you need to know ahead of the El Clasico that could decide the La Liga title. Tactical analysis, key battles, team news, and predictions from our panel of experts.',
    viewCount: 3200000,
    likeCount: 89000,
    commentCount: 7800,
    duration: '16:50',
    category: 'Football',
  },
  {
    videoId: 'pSudPeBkJWk',
    title: 'Australian Open 2025: Alcaraz Wins First Title in Melbourne',
    channelName: 'Bleacher Report',
    channelId: 'UC8-ZWfFvkRnN2Lfl8fFbK0A',
    thumbnailUrl: 'https://i.ytimg.com/vi/pSudPeBkJWk/mqdefault.jpg',
    publishedAt: daysAgo(14),
    description: 'Carlos Alcaraz captures his first Australian Open title with a stunning victory in the final. The young Spaniard cements his status as the future of tennis with this incredible performance.',
    viewCount: 2600000,
    likeCount: 72000,
    commentCount: 4500,
    duration: '13:20',
    category: 'Tennis',
  },
];

export function getMockVideos(category?: string): Video[] {
  if (!category || category === 'All') return MOCK_VIDEOS;
  return MOCK_VIDEOS.filter(v => v.category === category);
}
